In [12]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import os

from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from keras import optimizers
from keras import initializers

from sklearn.model_selection import train_test_split

os.chdir('C:/titanic')

matplotlib.style.use('ggplot')

%matplotlib inline

In [51]:
df = pd.read_csv('train1.csv', sep=',', header=0)
df = df.fillna(df.mean())
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0            1         0       3    0  22.0      1      0   7.2500
1            2         1       1    1  38.0      1      0  71.2833
2            3         1       3    1  26.0      0      0   7.9250
3            4         1       1    1  35.0      1      0  53.1000
4            5         0       3    0  35.0      0      0   8.0500

In [52]:
df['Survived'].value_counts(normalize=True)

0    0.616162
1    0.383838
Name: Survived, dtype: float64

In [53]:
DF = pd.read_csv('test1.csv', sep=',', header=0)
DF = DF.fillna(DF.mean())

In [54]:
y = df['Survived']
X = df.drop('Survived', axis=1)

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, test_size=0.33)

In [56]:
X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values

In [64]:
y_train_bin = np_utils.to_categorical(y_train)
y_test_bin = np_utils.to_categorical(y_test)

In [65]:
init2 = initializers.TruncatedNormal(mean=0.0, stddev=0.05, seed=73)
init3 = initializers.Constant(value=1e-3)

model3 = Sequential()
model3.add(Dense(7, input_dim=7, activation='relu', kernel_initializer=init2, bias_initializer=init3))
model3.add(Dense(10, activation='relu', kernel_initializer=init2, bias_initializer=init3))
model3.add(Dense(2, activation='relu', kernel_initializer=init2, bias_initializer=init3))

#SGD = optimizers.SGD(lr=0.02, momentum=0.8, decay=1e-6, nesterov=True)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train_bin, epochs=300, batch_size=None)

Epoch 1/300
596/596 [==============================] - 1s 1ms/step - loss: 7.9715 - acc: 0.0017 
Epoch 2/300
596/596 [==============================] - 0s 53us/step - loss: 7.9715 - acc: 0.0017
Epoch 3/300
596/596 [==============================] - 0s 37us/step - loss: 7.9715 - acc: 0.0017
Epoch 4/300
596/596 [==============================] - 0s 44us/step - loss: 7.9715 - acc: 0.0017
Epoch 5/300
596/596 [==============================] - 0s 44us/step - loss: 7.9715 - acc: 0.0017
Epoch 6/300
596/596 [==============================] - 0s 42us/step - loss: 7.9715 - acc: 0.0017
Epoch 7/300
596/596 [==============================] - 0s 35us/step - loss: 7.9715 - acc: 0.0017
Epoch 8/300
596/596 [==============================] - 0s 42us/step - loss: 7.9715 - acc: 0.0017
Epoch 9/300
596/596 [==============================] - 0s 37us/step - loss: 7.9715 - acc: 0.0017
Epoch 10/300
596/596 [==============================] - 0s 42us/step - loss: 7.9715 - acc: 0.0017
Epoch 11/300
596/596 [=======

596/596 [==============================] - 0s 39us/step - loss: 7.9715 - acc: 0.0017
Epoch 85/300
596/596 [==============================] - 0s 39us/step - loss: 7.9715 - acc: 0.0017
Epoch 86/300
596/596 [==============================] - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 87/300
596/596 [==============================] - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 88/300
596/596 [==============================] - 0s 32us/step - loss: 7.9715 - acc: 0.0017
Epoch 89/300
596/596 [==============================] - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 90/300
596/596 [==============================] - 0s 35us/step - loss: 7.9715 - acc: 0.0017
Epoch 91/300
596/596 [==============================] - ETA: 0s - loss: 7.9712 - acc: 0.0000e+0 - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 92/300
596/596 [==============================] - 0s 35us/step - loss: 7.9715 - acc: 0.0017
Epoch 93/300
596/596 [==============================] - 0s 35us/step - loss: 7.9715 - acc

596/596 [==============================] - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 167/300
596/596 [==============================] - 0s 35us/step - loss: 7.9715 - acc: 0.0017
Epoch 168/300
596/596 [==============================] - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 169/300
596/596 [==============================] - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 170/300
596/596 [==============================] - 0s 32us/step - loss: 7.9715 - acc: 0.0017
Epoch 171/300
596/596 [==============================] - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 172/300
596/596 [==============================] - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 173/300
596/596 [==============================] - 0s 32us/step - loss: 7.9715 - acc: 0.0017
Epoch 174/300
596/596 [==============================] - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 175/300
596/596 [==============================] - 0s 32us/step - loss: 7.9715 - acc: 0.0017
Epoch 176/300
596/596 [=

596/596 [==============================] - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 249/300
596/596 [==============================] - 0s 35us/step - loss: 7.9715 - acc: 0.0017
Epoch 250/300
596/596 [==============================] - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 251/300
596/596 [==============================] - 0s 35us/step - loss: 7.9715 - acc: 0.0017
Epoch 252/300
596/596 [==============================] - 0s 35us/step - loss: 7.9715 - acc: 0.0017
Epoch 253/300
596/596 [==============================] - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 254/300
596/596 [==============================] - 0s 32us/step - loss: 7.9715 - acc: 0.0017
Epoch 255/300
596/596 [==============================] - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 256/300
596/596 [==============================] - 0s 32us/step - loss: 7.9715 - acc: 0.0017
Epoch 257/300
596/596 [==============================] - 0s 34us/step - loss: 7.9715 - acc: 0.0017
Epoch 258/300
596/596 [=

In [61]:
scores = model.evaluate(X_test, y_test_bin)
print('\nAccuracy: %.2f%%' % (scores[1]*100))

295/295 [==============================] - 0s 965us/step

Accuracy: 0.17%


In [22]:
predictions = model.predict(X_test)

In [23]:
print(predictions[0:5])

[[7.9022840e-02 7.9750741e-01 1.2346975e-01]
 [4.2584452e-05 1.1136589e-03 9.9884367e-01]
 [1.0102865e-01 7.2210580e-01 1.7686556e-01]
 [4.0728780e-03 8.7957300e-02 9.0796983e-01]
 [9.9996495e-01 1.8990399e-05 1.6113609e-05]]


In [9]:
model2 = Sequential()
model2.add(Dense(9, input_dim=13, activation='relu'))
model2.add(Dense(10, activation='relu'))
model2.add(Dense(3, activation='softmax'))

sgd = optimizers.SGD(lr=0.02, decay=1e-6, momentum=0.8, nesterov=True)
model2.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])

model2.fit(X_train, y_train_bin, epochs=300, batch_size=10)

Epoch 1/300
119/119 [==============================] - 1s 7ms/step - loss: 11.3157 - acc: 0.2941
Epoch 2/300
119/119 [==============================] - 0s 143us/step - loss: 11.3775 - acc: 0.2941
Epoch 3/300
119/119 [==============================] - 0s 109us/step - loss: 11.3775 - acc: 0.2941
Epoch 4/300
119/119 [==============================] - 0s 126us/step - loss: 11.3775 - acc: 0.2941
Epoch 5/300
119/119 [==============================] - 0s 151us/step - loss: 11.3775 - acc: 0.2941
Epoch 6/300
119/119 [==============================] - 0s 109us/step - loss: 11.3775 - acc: 0.2941
Epoch 7/300
119/119 [==============================] - 0s 143us/step - loss: 11.3775 - acc: 0.2941
Epoch 8/300
119/119 [==============================] - 0s 109us/step - loss: 11.3775 - acc: 0.2941
Epoch 9/300
119/119 [==============================] - 0s 101us/step - loss: 11.3775 - acc: 0.2941
Epoch 10/300
119/119 [==============================] - 0s 134us/step - loss: 11.3775 - acc: 0.2941
Epoch 11/30

119/119 [==============================] - 0s 84us/step - loss: 11.3775 - acc: 0.2941
Epoch 164/300
119/119 [==============================] - 0s 109us/step - loss: 11.3775 - acc: 0.2941
Epoch 165/300
119/119 [==============================] - 0s 118us/step - loss: 11.3775 - acc: 0.2941
Epoch 166/300
119/119 [==============================] - 0s 109us/step - loss: 11.3775 - acc: 0.2941
Epoch 167/300
119/119 [==============================] - 0s 101us/step - loss: 11.3775 - acc: 0.2941
Epoch 168/300
119/119 [==============================] - 0s 118us/step - loss: 11.3775 - acc: 0.2941
Epoch 169/300
119/119 [==============================] - 0s 109us/step - loss: 11.3775 - acc: 0.2941
Epoch 170/300
119/119 [==============================] - 0s 92us/step - loss: 11.3775 - acc: 0.2941
Epoch 171/300
119/119 [==============================] - 0s 134us/step - loss: 11.3775 - acc: 0.2941
Epoch 172/300
119/119 [==============================] - 0s 134us/step - loss: 11.3775 - acc: 0.2941
Epoch 

Epoch 244/300
119/119 [==============================] - 0s 118us/step - loss: 11.3775 - acc: 0.2941
Epoch 245/300
119/119 [==============================] - 0s 126us/step - loss: 11.3775 - acc: 0.2941
Epoch 246/300
119/119 [==============================] - 0s 101us/step - loss: 11.3775 - acc: 0.2941
Epoch 247/300
119/119 [==============================] - 0s 118us/step - loss: 11.3775 - acc: 0.2941
Epoch 248/300
119/119 [==============================] - 0s 134us/step - loss: 11.3775 - acc: 0.2941
Epoch 249/300
119/119 [==============================] - 0s 126us/step - loss: 11.3775 - acc: 0.2941
Epoch 250/300
119/119 [==============================] - 0s 134us/step - loss: 11.3775 - acc: 0.2941
Epoch 251/300
119/119 [==============================] - 0s 76us/step - loss: 11.3775 - acc: 0.2941
Epoch 252/300
119/119 [==============================] - 0s 84us/step - loss: 11.3775 - acc: 0.2941
Epoch 253/300
119/119 [==============================] - 0s 109us/step - loss: 11.3775 - acc:

In [10]:
scores2 = model2.evaluate(X_test, y_test_bin)
print('\nAccuracy: %.2f%%' % (scores2[1]*100))

59/59 [==============================] - 0s 509us/step

Accuracy: 22.03%


In [11]:
predictions2 = model2.predict(X_test)

In [12]:
print(predictions2[0:5])

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [13]:
init2 = initializers.TruncatedNormal(mean=0.0, stddev=0.05, seed=12345)
init3 = initializers.Constant(value=1e-3)

model3 = Sequential()
model3.add(Dense(9, input_dim=13, activation='relu', kernel_initializer=init2, bias_initializer=init3))
model3.add(Dense(10, activation='relu', kernel_initializer=init2, bias_initializer=init3))
model3.add(Dense(3, activation='softmax', kernel_initializer=init2, bias_initializer=init3))

#sgd = optimizers.SGD(lr=0.02, decay=1e-6, momentum=0.8, nesterov=True)
model3.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model3.fit(X_train, y_train_bin, epochs=300, batch_size=10)

Epoch 1/300
119/119 [==============================] - 0s 2ms/step - loss: 1.0975 - acc: 0.2773
Epoch 2/300
119/119 [==============================] - 0s 101us/step - loss: 1.0821 - acc: 0.2941
Epoch 3/300
119/119 [==============================] - 0s 143us/step - loss: 1.0711 - acc: 0.2941
Epoch 4/300
119/119 [==============================] - 0s 126us/step - loss: 1.0676 - acc: 0.2941
Epoch 5/300
119/119 [==============================] - 0s 109us/step - loss: 1.0616 - acc: 0.2941
Epoch 6/300
119/119 [==============================] - 0s 134us/step - loss: 1.0580 - acc: 0.2941
Epoch 7/300
119/119 [==============================] - 0s 109us/step - loss: 1.0517 - acc: 0.2941
Epoch 8/300
119/119 [==============================] - 0s 118us/step - loss: 1.0432 - acc: 0.3193
Epoch 9/300
119/119 [==============================] - 0s 143us/step - loss: 1.0264 - acc: 0.4118
Epoch 10/300
119/119 [==============================] - 0s 126us/step - loss: 1.0085 - acc: 0.5714
Epoch 11/300
119/119 

119/119 [==============================] - 0s 134us/step - loss: 0.4523 - acc: 0.8403
Epoch 166/300
119/119 [==============================] - 0s 126us/step - loss: 0.4622 - acc: 0.8319
Epoch 167/300
119/119 [==============================] - 0s 134us/step - loss: 0.4446 - acc: 0.8739
Epoch 168/300
119/119 [==============================] - 0s 126us/step - loss: 0.4419 - acc: 0.8571
Epoch 169/300
119/119 [==============================] - 0s 118us/step - loss: 0.4497 - acc: 0.8235
Epoch 170/300
119/119 [==============================] - 0s 92us/step - loss: 0.4390 - acc: 0.8655
Epoch 171/300
119/119 [==============================] - 0s 101us/step - loss: 0.4295 - acc: 0.8655
Epoch 172/300
119/119 [==============================] - 0s 118us/step - loss: 0.4343 - acc: 0.8571
Epoch 173/300
119/119 [==============================] - 0s 118us/step - loss: 0.4324 - acc: 0.8235
Epoch 174/300
119/119 [==============================] - 0s 101us/step - loss: 0.4053 - acc: 0.8824
Epoch 175/300
1

In [14]:
scores3 = model3.evaluate(X_test, y_test_bin)
print('\nAccuracy: %.2f%%' % (scores3[1]*100))

59/59 [==============================] - 0s 695us/step

Accuracy: 93.22%


In [15]:
predictions3 = model3.predict(X_test)

In [16]:
print(predictions3[0:5])

[[4.0545925e-03 9.8125494e-01 1.4690524e-02]
 [1.0427895e-04 1.1911148e-03 9.9870455e-01]
 [7.8010416e-01 3.9014388e-02 1.8088149e-01]
 [1.2998685e-02 1.1845408e-03 9.8581684e-01]
 [9.9820054e-01 1.5669347e-03 2.3248995e-04]]
